### ISSUE TITLE
 Java 实现MVP的方式中，BaseMvpActivity的问题

### ISSUE THREAD

**Issue by bingdu0** [longforus/MVPExample#1]
java 实现MVP方式中的BaseMvpActivity 中有一个inited(),Kotlin的BaseActivity中实现了ITopView，如果我自己写一个BaseActivity，是不是也要写一个ITopView 接口，然后实现LifecycleOwner?可不可以分离一下java的BaseActivity 和kotlin的BaseActivity

**Comment by longforus** [comment]
@bingdu0 ITopView 接口的作用主要是帮助IView IPresenter 等写泛型,不做分层的话,泛型类型会无穷无尽,kotlin的接口里面已经实现了inited().但是java因为不支持抽象变量,所以需要在baseActivity中覆写,当然,你可以分离啊
