### ISSUE TITLE
kotlin要怎么使用

### ISSUE THREAD

**Issue by lxssss** [longforus/MVPExample#2]
kotlin要怎么使用这个插件？可以放一下kt的新建文件截图吗？是不是必须要和java混合才能用？

**Comment by longforus** [comment]
kotlin的话 生成的时候语言选择kotlin就可以了 @lxssss

**Comment by lxssss** [comment]
额。。我不知道为什么一个周末过去插件的弹窗界面就不一样了。。现在可以用了，之前是要求设置super presenter之类的，现在没有那个选项了
